// http://bernatferragut.com/
//@version=4

// Indicator's name
study(shorttitle = "T-Many-MA", title="Triple Many Moving Averages", overlay=true)

// MAPeriod is a variable used to store the indicator lookback period. In this case, from the input()
MA1Period   = input(50, title="MA1 Period")
MA1Type     = input(title="MA1 Type", defval="SMA", options=["RMA", "SMA", "EMA", "WMA"])

MA2Period   = input(100, title="MA2 Period")
MA2Type     = input(title="MA2 Type", defval="SMA", options=["RMA", "SMA", "EMA", "WMA"])

MA3Period   = input(200, title="MA3 Period")
MA3Type     = input(title="MA3 Type", defval="SMA", options=["RMA", "SMA", "EMA", "WMA"])

// Logical Conditions MA1
MA1 = if MA1Type == "SMA"
    sma(close, MA1Period)
else
    if MA1Type == "RMA"
        rma(close, MA1Period)
    else
        if MA1Type == "EMA"
            ema(close, MA1Period)
        else
            if MA1Type == "WMA"
                wma(close, MA1Period)
                    
// Logical Conditions MA2
MA2 = if MA2Type == "SMA"
    sma(close, MA2Period)
else
    if MA2Type == "RMA"
        rma(close, MA2Period)
    else
        if MA2Type == "EMA"
            ema(close, MA2Period)
        else
            if MA2Type == "WMA"
                wma(close, MA2Period)
                    
// Logical Conditions MA3
MA3 = if MA3Type == "SMA"
    sma(close, MA1Period)
else
    if MA3Type == "RMA"
        rma(close, MA3Period)
    else
        if MA3Type == "EMA"
            ema(close, MA3Period)
        else
            if MA3Type == "WMA"
                wma(close, MA3Period)
                    
// Plottong the graphs

plot(MA1, color=color.red, linewidth=1)
plot(MA2, color=color.green, linewidth=2)
plot(MA3, color=color.blue, linewidth=3)